FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

COPY tsconfig.json ./

RUN npm i typeorm typeorm-extension reflect-metadata pg ts-node

COPY ./src/db/ ./src/db/

COPY ./src/migrations/ ./src/migrations/

COPY ./src/entities/ ./src/entities/

CMD ["npm", "run", "db:migration:up"]